spring:
  application:
    name: transactions
  profiles:
    active: prod-new
  datasource:
    url: jdbc:postgresql://transaction-db.postgres.database.azure.com:5432/transactions
    username: postgres
    password: psg1vmware1!
