spring:
  application:
    name: transactions
  profiles:
    active: prod-azure-postgres
  datasource:
    url: jdbc:postgresql://transaction-db.postgres.database.azure.com:5432/transactions
    username: postgres@transaction-db.postgres.database.azure.com
    password: psg1vmware1!
