
spring:
  application:
    name: transactions
  profiles:
    active: prod-azure-postgres
  datasource:
    url: $(DB-USERNAME)
    username: Admin1
    password: Postgres1!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
azure:
  keyvault:
    enabled: true
    uri: https://cpukeyvault.vault.azure.net/
    client-id: ***
    client-key: ***
    tenant-id: ***
    token-acquire-timeout-seconds: 60
    refresh-interval: 1800000
