spring:
  application:
    name: transactions
  profiles:
    active: prod-azure-postgres
  datasource:
    url: $(DB-USERNAME)
    username: Admin1
    password: Postgres1!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: https://cpukeyvault.vault.azure.net/
          client:
            application-id: 5f125be4-c906-4298-8246-ceba13a2596d
        
     
