spring:
  application:
    name: transactions
  profiles:
    active: prod-azure-postgres
  datasource:
    url: jdbc:postgresql://transaction-db.postgres.database.azure.com:5432/transactions
    username: postgres@transaction-db.postgres.database.azure.com
    password: psg1vmware1!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
