apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: citizen-test-11
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: citizen-service
    apps.tanzu.vmware.com/auto-configure-actuators: "false"
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: citizen-test-11
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        boot.spring.io/version: 3.0.10-SNAPSHOT
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/app-live-view-appflavour-check
          spring-boot-convention/service-intent-postgres
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"citizen-service","apps.tanzu.vmware.com/auto-configure-actuators":"false","apps.tanzu.vmware.com/has-tests":"false","apps.tanzu.vmware.com/workload-type":"web"},"name":"citizen-test-11","namespace":"cpu"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"0"}},{"name":"gitops_server_address","value":"https://github.com/"},{"name":"gitops_repository_owner","value":"cpulcini2003"},{"name":"gitops_repository_name","value":"config-repo"},{"name":"gitops_ssh_secret","value":"git-secret"},{"name":"git_user_email","value":"cpulcini2003@gmail.com"},{"name":"git_user_name","value":"cpulcini2003"}],"serviceClaims":[{"name":"citizen-database","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ClassClaim","name":"citizen"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/cpulcini2003/citizen11"}}}}
        services.conventions.carto.run/postgres: postgresql/42.5.4
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: citizen-service
        apps.tanzu.vmware.com/auto-configure-actuators: "false"
        apps.tanzu.vmware.com/has-tests: "false"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: citizen-test-11
        conventions.carto.run/framework: spring-boot
        services.conventions.carto.run/postgres: workload
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: us-east1-docker.pkg.dev/tap-sandbox-dev/tapv-big-malamute/citizen-test-11-cpu@sha256:2200aa1305c83778103dd22a1cb41faa45e63a5de7a00550e5f7ada94ace0d48
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

